# Site settings
# These are used to personalize your new site.
title: Lexa Mosby # your name here
logo: "/images/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Computer-Science (class of 2022)
  <br /><br />
  <a href="https://github.com/LexaMO/LexaMO.github.io/blob/master/pdf/Lexamosby_resume.md">View My Resume</a>
  <br /><br />
  <a href="https://csuniv.joinhandshake.com/users/25814461">View My Handshake Profile</a>
repository: "csci-csu/csci-portfolio"
github_username:  LexaMO # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

